# Configuration for the Synapse Curation and Management Agentic System
#
# Store credentials and other configuration values here.
# For example:
# synapse:
#   username: "your_username"
#   api_key: "your_api_key" 

llm:
  # model should be in the format 'provider/model_name'
  model: "openrouter/google/gemini-2.5-flash"

  # API keys and other provider-specific settings.
  # These will be set as environment variables for crewai to use.
  # For openrouter, use "https://openrouter.ai/api/v1" for OPENAI_API_BASE
  # and your OpenRouter key for OPENAI_API_KEY.
  credentials:
    OPENROUTER_API_KEY: "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"
    OPENAI_API_BASE: "https://openrouter.ai/api/v1"

annotation_corrector:
  data_model_url: https://raw.githubusercontent.com/nf-osi/nf-metadata-dictionary/main/NF.jsonld"
  main_fileview: "syn16858331"