# Configuration for the Synapse Curation and Management Agentic System
llm:
  # model should be in the format 'provider/model_name'
  model: "openrouter/google/gemini-2.5-flash"

  agents:
    uncontrolled_vocab_normalizer:
      model: "openrouter/google/gemini-2.5-flash"
    freetext_corrector:
      model: "openrouter/google/gemini-2.5-flash"
    ontology_expert:
      model: "openrouter/google/gemini-2.5-pro"
    link_external_data_agent:
      model: "openrouter/google/gemini-2.5-flash"
    dataset_annotation_agent:
      model: "openrouter/google/gemini-2.5-flash"
    pride_sync_agent:
      model: "openrouter/google/gemini-2.5-flash"
    annotation_corrector:
      model: "openrouter/google/gemini-2.5-flash"

views:
  main_fileview: "syn16858331"
  study_long_text: "syn16787123"
  portal_initiatives: "syn24189696"
  portal_studies_view_staging: "syn52677631"
  ar_bypasses_in_nf_data_portal: "syn68414165"
  portal_publications: "syn16857542"

annotation_corrector:
  data_model_url: "https://raw.githubusercontent.com/nf-osi/nf-metadata-dictionary/main/NF.jsonld"
  data_model_repo_url: "https://github.com/nf-osi/nf-metadata-dictionary"